### ISSUE TITLE
Schema and tables not showing for SAP HANA

### ISSUE THREAD

**Issue by Lsubatin** [rickbergfalk/sqlpad#322]
Hi, 

Even if creating a connection with a schema name and the right permissions, the left-side panel does not show the list of tables for a schema. 

![image](https://user-images.githubusercontent.com/24896969/37856258-4e1671b2-2ed2-11e8-8a19-2d635aef0d52.png)

![image](https://user-images.githubusercontent.com/24896969/37856250-39c3ba4e-2ed2-11e8-8445-f8f04d54ff32.png)

Thanks, 
Lucia.

**Comment by rickbergfalk** [comment]
Thanks for reporting this @Lsubatin - I'll take a look into what might be going on.

**Comment by rickbergfalk** [comment]
I pushed an update to npm and docker, 2.5.3. Please give that a try, and press the "reload" button on the schema sidebar to force a refresh of the schema. I'm able to see tables and columns with a test instance that was set up.

Let me know how it goes

**Comment by g3rv4** [comment]
I'm having the same issue on a docker instance connecting to a docker instance of SQL Server. I'm seeing an ajax request to `/api/schema-info/tqyQyvPvq4QFRp6k` that never gets replied to.

I've tested that the connection works (that's what sqlpad says when adding it). Is there any more info I can get you? I'll try with an older version

**Comment by g3rv4** [comment]
Version 2.5.1 works fine for me :D

**Comment by rickbergfalk** [comment]
Thanks @g3rv4! Are you saying that 2.5.1 works for you, but 2.5.3 does not?

**Comment by g3rv4** [comment]
@rickbergfalk that is correct! I’m running both sqlpad and sql server on docker containers in MacOS fwiw. On 2.5.3, it gets stuck. On 2.5.1, it works fine.

I may get to play with it on the weekend... nodejs is not my favorite language but sqlpad makes me want to play with it ;)

Would getting you a docker-compose.yml with a repto help you debug it?

**Comment by rickbergfalk** [comment]
Interesting - I've noticed that api has issues in TravisCI (which runs in a docker environment), but it does not have issues when I run sqlpad locally. 

A docker-compose.yml that can reproduce the issue would be great! I haven't been able to reproduce it, and trying to debug the issue remotely via logs has been difficult.

**Comment by g3rv4** [comment]
@rickbergfalk I've got a local repro. Here are the steps:

### Start both sql server and sqlpad containers.

I've done so with this `docker-compose.yml` (my folder is `sqlpadwithissues`, that's going to be relevant for the docker container names)

```
version: '2'
services:
  mssql:
    image: 'microsoft/mssql-server-linux:2017-latest'
    restart: always
    hostname: 'mssql'
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=SuperP4ssw0rd!
      - MSSQL_PID=Express
  sqlpad:
    image: 'sqlpad/sqlpad:2.5.3'
    hostname: 'sqlpad'
    ports:
      - '3000:3000'
```

### Create a database on the sql server instance

Connect to the database server (here is where the folder name is relevant)

```
docker exec -it sqlpadwithissues_mssql_1 /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P SuperP4ssw0rd!
```

Create the database

```
1> CREATE DATABASE LetsTestIt;
2> Go
```

### Connect to sqlpad, configure the connection and profit!

![GifWithTheIssue](https://gmc.uy/profitNotProfit.gif)
