### ISSUE TITLE
Prepared statements failing (mysql/MariaDB, sqlpad > 4.3)

### ISSUE THREAD

**Issue by mahaesin** [rickbergfalk/sqlpad#695]
Running sqlpad 4.4 and latest (from docker hub; MariaDB container pinned to 10.5.3) i can't use prepare/execute statements. Even simple examples based on https://mariadb.com/kb/en/prepare-statement/#example
fail:
```
PREPARE stmt FROM 'SELECT @x;';
SET @x = 1;
EXECUTE stmt;
```
-->
`ER_UNKNOWN_STMT_HANDLER: Unknown prepared statement handler (stmt) given to EXECUTE`

```
SET @table = "some_table";
SET @sql = CONCAT('SELECT * FROM ', @table);
PREPARE stmt FROM @sql;
EXECUTE stmt;
```
-->
`ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'NULL' at line 1`

Both examples work with sqlpad 4.3 (from docker hub) and using MariaDBs console.

**Comment by mahaesin** [comment]
My (stripped down) configs:
config.json:
```
{
  "admin": "admin@sqlpad.com",
  "adminPassword": "admin",
  "appLogLevel": "info",
  "webLogLevel": "warn",
  "seedDataPath": "/etc/sqlpad/seed-data",
  "disableAuth": "true",
  "disableAuthDefaultRole": "editor",
  "connections": {
    "mydb": {
      "name": "My DB",
      "driver": "mysql",
      "host": "db",
      "database": "mydb",
      "username": "dbuser",
      "password": "password",
      "multiStatementTransactionEnabled": true,
      "idleTimeoutSeconds": 86400
    }
  }
}
```

docker-compose.yml:
```
version: '3'
services:
  db:
    image: mariadb:10.5.3
    restart: always
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=mydb
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=password
    volumes:
      - ./db:/var/lib/mysql
  sqlpad:
    image: sqlpad/sqlpad:4.4
    ports:
      - '3000:3000'
    environment:
      SQLPAD_CONFIG: /etc/sqlpad/config.json
      SQLPAD_BASE_URL: /sqlpad
    volumes:
      - ./config.json:/etc/sqlpad/config.json
      - ./seed-data:/etc/sqlpad/seed-data

```
I'm trying out sqlpad the last two days and like it a lot.
Thank you!
